### PR TITLE
Donovan/credits page

### PR DESCRIPTION
**Pull request by dfardev**
Separate Scene For Credits that can route the user back to the menu or to play again

### CODE REVIEW

**Comment by dotunadegbite** [comment]
Was this done all with an animation within the UI or was this an animation on a game object holding all of the credit text?

**Comment by dfardev** [comment]
Animation on a game object within the UI. There's a record option that I used on the credit's parent object

**Comment by dotunadegbite** [comment]
> 

Will this work with the WebGL version? I have a worry that differing aspect ratio may cause this to work unexpectedly.

**Comment by dfardev** [comment]
I am not sure. If I merge now could you get a webGL build up to test for the meeting?

**Comment by dfardev** [comment]
Oh it may be better if I just go test the version on this branch

**Comment by dotunadegbite** [comment]
> I am not sure. If I merge now could you get a webGL build up to test for the meeting?

Nah. You should be able to spin up a webgl build locally on your side though. Through the Build and run options under project settings

**Pull request closed without merging**
